name: 'Export marimo notebooks using marimushka'
description: 'Export of notebooks and apps'

inputs:
  template:
    description: 'The html.j2 template for export'
    required: false

runs:
  using: "composite"
  steps:
    - name: ðŸ“¦ Checkout repository
      uses: actions/checkout@v4

    - name: ðŸš€ Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: '3.12'
        cache-dependency-glob: '/dev/null'
        ignore-nothing-to-cache: 'true'

    - name: ðŸ› ï¸ Export marimo notebooks to WebAssembly
      shell: bash
      run: |
        # Path to default template in this action's directory
        DEFAULT_TEMPLATE="${GITHUB_ACTION_PATH}/templates/default.html.j2"

        # Use provided template if set, otherwise fallback
        if [ -z "${{ inputs.template }}" ]; then
          echo "No template provided. Using default: $DEFAULT_TEMPLATE"
          TEMPLATE="$DEFAULT_TEMPLATE"
        else
          echo "Using provided template: ${{ inputs.template }}"
          TEMPLATE="${{ inputs.template }}"
        fi

        # Create a random temporary directory
        TMP_DIR=$(mktemp -d)
        echo "Using temporary directory: $TMP_DIR"

        # Export notebooks to the temporary directory
        uvx marimushka --template "$TEMPLATE" --output-dir "$TMP_DIR"

        # Save the temp directory for the next step
        echo "TMP_DIR=$TMP_DIR" >> "$GITHUB_ENV"

    - name: ðŸ“¤ Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ env.TMP_DIR }}

    - name: ðŸ§¹ Clean up temporary folder
      shell: bash
      run: |
        if [ -d "${{ env.TMP_DIR }}" ]; then
          echo "Deleting temp dir: ${{ env.TMP_DIR }}"
          rm -rf "${{ env.TMP_DIR }}"
        else
          echo "Temp dir already gone or not set."
        fi
